name: 'Azure App Configuration Sync (Deprecated)'
description: 'DEPRECATED: Use Azure CLI action instead. Follow [these instructions](https://aka.ms/appconfig/githubactions) to set up.'
inputs:
  configurationFile:
    description: 'Path to the configuration file in the repo, relative to the repo root. Also supports glob patterns and multiple files'
    required: true
  format:
    description: 'Format of the configuration file. Valid values are: json, yaml, properties'
    required: true
  connectionString:
    description: 'Connection string for the App Configuration instance'
    required: true
  separator:
    description: 'Separator used when flattening the configuration file to key-value pairs'
    required: true
  strict:
    description: 'Specifies whether to use a strict sync which will make the App Configuration instance exactly match the configuration file (deleting key-values not in the configuration file). Defaults to false'
    required: false
  prefix:
    description: 'Prefix that will be added to the front of the keys'
    required: false
  label:
    description: 'Label to use when setting the key-value pairs. If not specified, a null label will be used'
    required: false
  depth:
    description: 'Max depth (positive number) for flattening the configuration file'
    required: false
  tags:
    description: 'Stringified form of a JSON object with the following shape: { [propertyName: string]: string; }'
    required: false
  contentType:
    description: 'Content type associated with the values'
    required: false    
runs:
  using: 'node20'
  main: 'lib/index.js'
